### ISSUE TITLE
Multiples of ten describing other multiples of ten require an intermediary number. I.e "twenty thousand" doesn't work

### ISSUE THREAD

**Issue by JeremyStepp** [MycroftAI/lingua-franca#81]
"twenty thousand" returns "20". The only way I have found to get this sort of situation to work is to add an extra number. "twenty four thousand" properly returns "24000".

**Comment by krisgesling** [comment]
Thanks for these bug reports Jeremy!

They all look very clear and splitting them between issues will make it easier to track they each issue has been addressed.

**Comment by ChanceNCounter** [comment]
Related to #86 

I suspect this snippet, which I've been messing with, but haven't nailed down:

https://github.com/MycroftAI/lingua-franca/blob/5ac3a86f1b5d1f2f97722ecb14408411a0fc663f/lingua_franca/lang/parse_en.py#L446-L463

If this is extended also to handle the word *after* next, you see some improvement, but it does not resolve the actual summing issue, which is the root of this bug,

**Comment by ChanceNCounter** [comment]
Finding: it returns the correct result for *powers* of ten.

```python
>>> for i in tens:
...   parse.extract_number(i + " million")
... 
10000000
20
30
40
50
60
70
80
90
100000000

**Comment by ChanceNCounter** [comment]
Confirmed that snippet is the culprit.
